development:
    paypal_email: friccobono@hopeforchange.org
    paypal_secret: foobar
    paypal_cert_id: J2H5PSMFSJ6E2
    paypal_url: https://www.sandbox.paypal.com/cgi-bin/webscr

test:
    paypal_email: test@example.com
    paypal_secret: testsecret
    paypal_cert_id: X123456789
    paypal_url: testpaypalurl

production:
    paypal_email: friccobono@hopeforchange.org
    paypal_secret: foobar
    paypal_cert_id: J2H5PSMFSJ6E2
    paypal_url: https://www.sandbox.paypal.com/cgi-bin/webscr
